const light = {
  text: {
    default: '#0D1D2B',
    strong: '#6E7781',
    subdued: '#858E95',
    disabled: '#868d95',
    interactive: {
      primary: {
        default: '#034ac2',
        hovered: '#034fcc',
        pressed: '#0465b9',
        depressed: '#0560b0',
        disabled: '#868e95',
      },
      success: {
        default: '#4A934A',
        hovered: '#4e9c4e',
        pressed: '#458a45',
        depressed: '#408140',
        disabled: '#868e95',
      },
      info: {
        default: '#40869b',
        hovered: '#448fa6',
        pressed: '#3b7c90',
        depressed: '#377385',
        disabled: '#868e95',
      },
      warning: {
        default: '#a87937',
        hovered: '#b4823b',
        pressed: '#9c7033',
        depressed: '#90682f',
        disabled: '#868e95',
      },
      critical: {
        default: '#a32a2c',
        hovered: '#ad2c2f',
        pressed: '#992729',
        depressed: '#8f2427',
        disabled: '#868e95',
      },
      charm: {
        default: '#852a82',
        hovered: '#8d2b88',
        pressed: '#7c297c',
        depressed: '#742876',
        disabled: '#868e95',
      },
    },
    textOn: {
      primary: {
        default: '#FFFFFF',
        subdued: '#0560b0',
      },
      interactive: {
        default: '#FFFFFF',
        disabled: '#6E7780',
      },
      critical: {
        default: '#FFFFFF',
        subdued: '#8f2427',
      },
      success: {
        default: '#FFFFFF',
        subdued: '#408140',
      },
      info: {
        default: '#FFFFFF',
        subdued: '#377385',
      },
      warning: {
        default: '#FFFFFF',
        subdued: '#90682F',
      },
      charm: {
        default: '#FFFFFF',
        subdued: '#742876',
      },
      inverse: {
        default: '#FFFFFF',
      },
    },
  },
  icon: {
    default: '#0D1D2C',
    subdued: '#868E95',
    subtle: '#9ea5ab',
    hovered: '#192837',
    pressed: '#0c1c2a',
    disabled: '#868E95',
    interactive: {
      primary: {
        default: '#036ac2',
        hovered: '#036fcc',
        pressed: '#0465b9',
        depressed: '#0560b0',
        disabled: '#868e95',
      },
      success: {
        default: '#4a934a',
        hovered: '#4e9c4e',
        pressed: '#458a45',
        depressed: '#408140',
        disabled: '#868e95',
      },
      info: {
        default: '#40869b',
        hovered: '#448fa6',
        pressed: '#3b7c90',
        depressed: '#377385',
        disabled: '#868e95',
      },
      warning: {
        default: '#a87937',
        hovered: '#b4823b',
        pressed: '#9c7033',
        depressed: '#90682f',
        disabled: '#868e95',
      },
      critical: {
        default: '#a32a2c',
        hovered: '#ad2c2f',
        pressed: '#992729',
        depressed: '#8f2427',
        disabled: '#868e95',
      },
      charm: {
        default: '#852a82',
        hovered: '#8d2b88',
        pressed: '#7c297c',
        depressed: '#742876',
        disabled: '#868e95',
      },
    },
    iconOn: {
      interactive: {
        default: '#FFFFFF',
        disabled: '#6E7780',
      },
      primary: {
        default: '#FFFFFF',
        subdued: '#0560b0',
      },
      critical: {
        default: '#FFFFFF',
        subdued: '#A32A2C',
      },
      success: {
        default: '#FFFFFF',
        subdued: '#408140',
      },
      info: {
        default: '#FFFFFF',
        subdued: '#40869b',
      },
      warning: {
        default: '#FFFFFF',
        subdued: '#a87937',
      },
      charm: {
        default: '#FFFFFF',
        subdued: '#852a82',
      },
      inverse: {
        default: '#FFFFFF',
      },
    },
    price: {
      priceUp: '#28A745',
      priceDown: '#EA3943',
    },
  },
  background: {
    interactive: {
      primary: {
        default: '#017DE8',
        hovered: '#0e84e9',
        pressed: '#0278df',
        depressed: '#0273d5',
        active: '#036ac2',
        disabled: '#E7E8EA',
      },
      secondary: {
        default: '#f5f6f7',
        hovered: '#F0F1F2',
        pressed: '#ECEDEE',
        depressed: '#e7e8ea',
        active: '#0D1D2C',
        disabled: '#E7E8EA',
      },
      success: {
        default: '#4a934a',
        hovered: '#4e9c4e',
        pressed: '#458a45',
        depressed: '#408140',
        active: '#376e37',
        disabled: '#E7E8EA',
      },
      info: {
        default: '#40869b',
        hovered: '#448fa6',
        pressed: '#3b7c90',
        depressed: '#377385',
        active: '#2d606f',
        disabled: '#E7E8EA',
      },
      warning: {
        default: '#a87937',
        hovered: '#b4823b',
        pressed: '#9c7033',
        depressed: '#90682f',
        active: '#785727',
        disabled: '#E7E8EA',
      },
      critical: {
        default: '#a32a2c',
        hovered: '#ad2c2f',
        pressed: '#992729',
        depressed: '#8f2427',
        active: '#7A1F21',
        disabled: '#E7E8EA',
      },
      notification: {
        default: '#e6002e',
      },
      charm: {
        default: '#852a82',
        hovered: '#8d2b88',
        pressed: '#7c297c',
        depressed: '#742876',
        active: '#632669',
        disabled: '#E7E8EA',
      },
      tertiary: {
        hovered: '#f9f9fa',
        pressed: '#f5f6f7',
        depressed: '#f0f1f2',
        active: '#ecedee',
      },
      inverse: {
        default: '#0d1d2c',
        hovered: '#192837',
        pressed: '#0c1c2a',
        depressed: '#0c1a28',
        active: '#0a1723',
        disabled: '#6e7780',
      },
    },
  },
  elevation: {
    background: '#F5F6F7',
    overlay: '#0D1D2C33',
    surface: {
      default: '#FFFFFF',
      subtle: '#f9f9fa',
      subdued: '#f5f6f7',
      disabled: '#e7e8ea',
      hovered: '#f0f1f2',
      pressed: '#ecedee',
      onTop: '#FFFFFF',
      primary: {
        default: '#dbedfc',
        subdued: '#F0F7FE',
        subduedHovered: '#E6F2FD',
        subduedPressed: '#E0EFFC',
        subduedActive: '#CCE5FA',
      },
      success: {
        default: '#d6edd6',
        subdued: '#EFF8EF',
        subduedHovered: '#EBF6EB',
        subduedPressed: '#e8f5e8',
        subduedActive: '#DEF1DE',
      },
      info: {
        default: '#d6eff7',
        subdued: '#EFF9FC',
        subduedHovered: '#EBF7FB',
        subduedPressed: '#e8f6fa',
        subduedActive: '#DEF2F8',
      },
      warning: {
        default: '#fbebd3',
        subdued: '#FDF7ED',
        subduedHovered: '#FDF5EA',
        subduedPressed: '#fdf4e6',
        subduedActive: '#FCEFDC',
      },
      critical: {
        default: '#f2cccd',
        subdued: '#FAEBEB',
        subduedHovered: '#F9E7E7',
        subduedPressed: '#f8e3e3',
        subduedActive: '#F5D6D7',
      },
      neutral: {
        default: '#cfd2d5',
        subdued: '#f0f1f2',
        subduedHovered: '#ecedee',
        subduedPressed: '#e7e8ea',
        subduedSelected: '#d8dbdd',
      },
      charm: {
        default: '#edcbe9',
        subdued: '#f8eaf6',
        subduedHovered: '#f6e6f4',
        subduedPressed: '#f5e2f3',
        subduedActive: '#f1d5ed',
      },
      selected: {
        default: '#F5F5F5',
        hovered: '#F0F0F0',
        pressed: '#ededed',
        active: '#ebebeb',
        disabled: '#e6e6e6',
      },
      inverse: {
        default: '#0D1D2C',
        hovered: '#192837',
        pressed: '#0c1c2a',
        depressed: '#0c1a28',
        active: '#0a1723',
        disabled: '#6E7780',
      },
    },
  },
  border: {
    default: '#d8dbdd',
    subdued: '#E2E4E6',
    subtle: '#ECEDEE',
    faint: '#F5F6F7',
    success: {
      default: '#4a934a',
      subdued: '#BEE3BE',
      disabled: '#DEF1DE',
    },
    info: {
      default: '#40869b',
      subdued: '#BDE5F1',
      disabled: '#DEF2F8',
    },
    warning: {
      default: '#a87937',
      subdued: '#F9DEB8',
      disabled: '#FCEFDC',
    },
    critical: {
      default: '#a32a2c',
      subdued: '#EBAEAF',
      disabled: '#F5D6D7',
    },
    charm: {
      default: '#852a82',
      subdued: '#e3acdc',
      disabled: '#f1d5ed',
    },
    textInput: {
      default: '#E2E4E6',
      selected: '#0273d5',
      hovered: '#cfd2d5',
      error: '#b82f32',
    },
    focus: {
      default: '#0273d5',
    },
    inverse: {
      default: '#6E7780',
    },
  },
} as const

export default light
