api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: false
      targetPort: {{ targetPortOrDefault 8080 }}
      transport: http
      allowInsecure: true
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: connectionstrings--todosdb
        value: Host=todos-postgres;Port=5432;Username=postgres;Password={{ securedParameter "todos_postgres_password" }};Database=todosdb
      - name: todosdb-password
        value: '{{ securedParameter "todos_postgres_password" }}'
  template:
    containers:
      - image: {{ .Image }}
        name: apiservice
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
            value: "true"
          - name: HTTP_PORTS
            value: '{{ targetPortOrDefault 0 }}'
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY
            value: in_memory
          - name: TODOSDB_DATABASENAME
            value: todosdb
          - name: TODOSDB_HOST
            value: todos-postgres
          - name: TODOSDB_JDBCCONNECTIONSTRING
            value: jdbc:postgresql://todos-postgres:5432/todosdb
          - name: TODOSDB_PORT
            value: "5432"
          - name: TODOSDB_URI
            value: postgresql://postgres:{{ uriEncode (securedParameter "todos_postgres_password" )}}@todos-postgres:5432/todosdb
          - name: TODOSDB_USERNAME
            value: postgres
          - name: ConnectionStrings__todosdb
            secretRef: connectionstrings--todosdb
          - name: TODOSDB_PASSWORD
            secretRef: todosdb-password
    scale:
      minReplicas: 1
tags:
  azd-service-name: apiservice
  aspire-resource-name: apiservice
